In [1]:
import pickle
import pandas as pd

with open("titanic_step4_importance_train.pickle", "rb") as pickle_filename :
    train_importance = pickle.load(pickle_filename)
with open("titanic_step4_importance_test.pickle", "rb") as pickle_filename :
    test_importance = pickle.load(pickle_filename)
with open("titanic_step4_importance_train_y.pickle", "rb") as pickle_filename :
    train_answer = pickle.load(pickle_filename)

In [2]:
import numpy as np
import pandas as pd
import warnings

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from scipy import stats

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

warnings.filterwarnings("ignore")

In [3]:
hyperparams = {
    "C": stats.uniform(0, 50), # 하이퍼 파라미터 값을 결정, 4, 13, 20 -> 크면 : 최대한 정확도 근접 (규제 강도 높인다) : 과적합 위험, 작으면 : 대충, 대략
    "gamma": stats.uniform(0, 1)
}

gd = RandomizedSearchCV(
    estimator=SVC(random_state=1),
    param_distributions=hyperparams,
    n_iter=100,
    cv=5,
    scoring="accuracy",
    random_state=1,
    n_jobs=-1
)

gd.fit(train_importance, train_answer.values.ravel())
print(gd.best_score_)
print(gd.best_params_)

df = pd.DataFrame(gd.cv_results_)
print(df[["params", "mean_test_score"]])

0.8397448105122833
{'C': np.float64(2.227593927238086), 'gamma': np.float64(0.1074941291060929)}
                                               params  mean_test_score
0   {'C': 20.8511002351287, 'gamma': 0.72032449344...         0.811560
1   {'C': 0.005718740867244332, 'gamma': 0.3023325...         0.619641
2   {'C': 7.337794540855652, 'gamma': 0.0923385947...         0.832991
3   {'C': 9.313010568883545, 'gamma': 0.3455607270...         0.818308
4   {'C': 19.838373711533496, 'gamma': 0.538816734...         0.820574
..                                                ...              ...
95  {'C': 13.164838524355549, 'gamma': 0.065961090...         0.834120
96  {'C': 36.753298164433474, 'gamma': 0.772178029...         0.809306
97  {'C': 45.3907926251762, 'gamma': 0.93197206919...         0.807046
98  {'C': 0.6975786487798508, 'gamma': 0.234362086...         0.831829
99  {'C': 30.83891785008288, 'gamma': 0.9490163206...         0.805916

[100 rows x 2 columns]

In [4]:
hyperparams = {
    "C": [10, 15, 20, 23, 25, 30, 50],
    "gamma": [0.001, 0.01, 0.05, 0.06, 0.07, 0.1]
}

gd = GridSearchCV(
    estimator=SVC(random_state=1),
    param_grid=hyperparams,
    verbose=True,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

gd.fit(train_importance, train_answer.values.ravel())
print(gd.best_score_)
print(gd.best_params_)

df = pd.DataFrame(gd.cv_results_)
print(df[["params", "mean_test_score"]])

Fitting 5 folds for each of 42 candidates, totalling 210 fits
0.8352440804926046
{'C': 15, 'gamma': 0.05}
                       params  mean_test_score
0   {'C': 10, 'gamma': 0.001}         0.791164
1    {'C': 10, 'gamma': 0.01}         0.829563
2    {'C': 10, 'gamma': 0.05}         0.831854
3    {'C': 10, 'gamma': 0.06}         0.834114
4    {'C': 10, 'gamma': 0.07}         0.832984
5     {'C': 10, 'gamma': 0.1}         0.831861
6   {'C': 15, 'gamma': 0.001}         0.795664
7    {'C': 15, 'gamma': 0.01}         0.826185
8    {'C': 15, 'gamma': 0.05}         0.835244
9    {'C': 15, 'gamma': 0.06}         0.829607
10   {'C': 15, 'gamma': 0.07}         0.831854
11    {'C': 15, 'gamma': 0.1}         0.827347
12  {'C': 20, 'gamma': 0.001}         0.802444
13   {'C': 20, 'gamma': 0.01}         0.827315
14   {'C': 20, 'gamma': 0.05}         0.827347
15   {'C': 20, 'gamma': 0.06}         0.829594
16   {'C': 20, 'gamma': 0.07}         0.830718
17    {'C': 20, 'gamma': 0.1}         0.823964
18  {'C': 23, 'gamma': 0.001}         0.808075
19   {'C': 23, 'gamma': 0.01}         0.828439
20   {'C': 23, 'gamma': 0.05}         0.828477
21   {'C': 23, 'gamma': 0.06}         0.825081
22   {'C': 23, 'gamma': 0.07}         0.831854
23    {'C': 23, 'gamma': 0.1}         0.820574
24  {'C': 25, 'gamma': 0.001}         0.811464
25   {'C': 25, 'gamma': 0.01}         0.827322
26   {'C': 25, 'gamma': 0.05}         0.832991
27   {'C': 25, 'gamma': 0.06}         0.826205
28   {'C': 25, 'gamma': 0.07}         0.829594
29    {'C': 25, 'gamma': 0.1}         0.819444
30  {'C': 30, 'gamma': 0.001}         0.814861
31   {'C': 30, 'gamma': 0.01}         0.830705
32   {'C': 30, 'gamma': 0.05}         0.828471
33   {'C': 30, 'gamma': 0.06}         0.827341
34   {'C': 30, 'gamma': 0.07}         0.826205
35    {'C': 30, 'gamma': 0.1}         0.819438
36  {'C': 50, 'gamma': 0.001}         0.822789
37   {'C': 50, 'gamma': 0.01}         0.832959
38   {'C': 50, 'gamma': 0.05}         0.826205
39   {'C': 50, 'gamma': 0.06}         0.819438
40   {'C': 50, 'gamma': 0.07}         0.816048
41    {'C': 50, 'gamma': 0.1}         0.821691

In [5]:
learning_rate = [0.01, 0.05, 0.1, 0.2] # 만약 최초 모델을 통해서 학습 -> 오류 -> 어느정도 범위까지 줄여나가게 할 것인가? = 학습률
n_estimators = [100, 1000, 2000]
max_depth = [3, 5, 10, 15]

hyerparams = {
    "learning_rate": learning_rate,
    "n_estimators": n_estimators,
    "max_depth": max_depth
}

gd = GridSearchCV(
    estimator= GradientBoostingClassifier(random_state=1),
    param_grid=hyerparams,
    verbose=True,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

gd.fit(train_importance, train_answer.values.ravel())
print(gd.best_score_)
print(gd.best_params_)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
0.8431282930235511
{'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 1000}

In [19]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

hyperparams = {
    "penalty": ["l1", "l2", "elasticnet"],
    "C": stats.uniform(0, 1000)
}

gd = RandomizedSearchCV(
    estimator= LogisticRegression(random_state=1, solver='lbfgs', max_iter=1000),
    param_distributions=hyperparams,
    n_iter=100,
    cv=5,
    scoring="accuracy",
    random_state=1,
    n_jobs=-1
)

gd.fit(train_importance, train_answer.values.ravel())
print(gd.best_score_)
print(gd.best_params_)

0.8409064940011428
{'C': np.float64(491.5731592803383), 'penalty': 'l2'}

In [7]:
np.linspace(700, 900, 10)

array([700.        , 722.22222222, 744.44444444, 766.66666667,
       788.88888889, 811.11111111, 833.33333333, 855.55555556,
       877.77777778, 900.        ])

In [8]:
penalty = ["l1", "l2"]
C = np.linspace(700, 900, 200)

hyperparams = {
    "penalty": penalty,
    "C": C
}

gd = GridSearchCV(
    estimator=LogisticRegression(random_state=1),
    param_grid=hyperparams,
    verbose=True,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

gd.fit(train_importance, train_answer.values.ravel())
print(gd.best_score_)
print(gd.best_params_)

Fitting 5 folds for each of 400 candidates, totalling 2000 fits
0.8409064940011426
{'C': np.float64(706.0301507537688), 'penalty': 'l2'}

In [20]:
!pip install bayesian-optimization

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bayesian-optimization in /Users/admin/Library/Python/3.9/lib/python/site-packages (3.1.0)
Requirement already satisfied: colorama>=0.4.6 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from bayesian-optimization) (0.4.6)
Requirement already satisfied: numpy>=1.25 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from bayesian-optimization) (2.0.2)
Requirement already satisfied: scikit-learn>=1.0.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from bayesian-optimization) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from bayesian-optimization) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from scikit-learn>=1.0.0->bayesian-optimization) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from scikit-learn>=1.0.0->bayesian-optimization) (3.6.0)

In [9]:
import numpy as np
from xgboost import XGBClassifier
from bayes_opt import BayesianOptimization
from sklearn.model_selection import cross_val_score

pbounds = {
    "learning_rate": (0.01, 0.5), # 하나의 트리가 다음번째 트리에 얼마나 강하게 반영이 될지 결정하는 속성
    "n_estimators": (100, 1000), # 몇 개의 트리를 만들것인가?
    "max_depth": (3, 10), # XGBoost -> 3~6적합
    "min_child_weight": (0, 10), # 트리 내 질문을 하려고 할 때, 샘플 데이터 양
    "subsample": (0.5, 1.0), # 각 트리를 학습할 때, 사용하는 데이터 비율
    "colsample_bytree": (0.5, 1.0), # 학습시키고자 하는 데이터의 컬럼을 전체다 사용? 일부만 사용?
    "gamma": (0, 5) # 성능 개선의 최대치
}

def xgbost_hyper_param(learning_rate, n_estimators, max_depth, min_child_weight, subsample, colsample_bytree, gamma) :
    max_depth = int(max_depth)
    n_estimators = int(n_estimators)
    
    clf = XGBClassifier(
        max_depth = max_depth,
        min_child_weight = min_child_weight,
        learning_rate = learning_rate,
        n_estimators = n_estimators,
        subsample = subsample,
        colsample_bytree = colsample_bytree,
        gamma = gamma,
        random_state = 1,
        eval_metric = "logloss"
    )
    return np.mean(cross_val_score(clf, train_importance, train_answer, cv=5, scoring="accuracy"))

optimizer = BayesianOptimization(f=xgbost_hyper_param, pbounds=pbounds, random_state=1)
optimizer.maximize(init_points=10, n_iter=100)

|   iter    |  target   | learni... | n_esti... | max_depth | min_ch... | subsample | colsam... |   gamma   |
-------------------------------------------------------------------------------------------------------------
| 1         | 0.8194375 | 0.2143407 | 748.29204 | 3.0008006 | 3.0233257 | 0.5733779 | 0.5461692 | 0.9313010 |
| 2         | 0.8182822 | 0.1793247 | 457.09072 | 6.7717171 | 4.1919451 | 0.8426097 | 0.6022261 | 4.3905871 |
| 3         | 0.8070335 | 0.0234199 | 703.42075 | 5.9211336 | 5.5868982 | 0.5701934 | 0.5990507 | 4.0037228 |
| 4         | 0.8216784 | 0.4844481 | 382.08176 | 7.8462583 | 8.7638915 | 0.9473033 | 0.5425221 | 0.1952739 |
| 5         | 0.8115089 | 0.0932169 | 890.32825 | 3.6884278 | 4.2110762 | 0.9789447 | 0.7665826 | 3.4593855 |
| 6         | 0.8318161 | 0.1646026 | 717.85083 | 8.8423797 | 0.1828827 | 0.8750721 | 0.9944305 | 3.7408282 |
| 7         | 0.8295816 | 0.1474175 | 810.35139 | 3.7225820 | 4.4789352 | 0.9542977 | 0.6468070 | 1.4388766 |
| 8         | 0.8329714 | 0.0737140 | 117.43026 | 7.7518487 | 2.1162811 | 0.6327733 | 0.7457865 | 0.2668127 |
| 9         | 0.8137751 | 0.2913176 | 232.05571 | 7.1251387 | 6.9975836 | 0.5511672 | 0.7070279 | 3.4720007 |
| 10        | 0.8250555 | 0.2129478 | 144.95811 | 6.7512748 | 6.6379464 | 0.7574445 | 0.9722973 | 2.9327752 |
| 11        | 0.8205421 | 0.0910235 | 175.44776 | 5.3171175 | 5.9138690 | 0.6977401 | 0.8880526 | 3.8402380 |
| 12        | 0.8081381 | 0.3118184 | 390.43865 | 5.8224530 | 8.0412946 | 0.6149061 | 0.6790616 | 3.7915660 |
| 13        | 0.8363613 | 0.1761053 | 117.95505 | 6.9966324 | 1.6669358 | 0.7730750 | 0.5326313 | 0.2787153 |
| 14        | 0.8126706 | 0.3678976 | 121.14944 | 5.6539184 | 1.9046969 | 0.5447413 | 1.0       | 0.0228782 |
| 15        | 0.8352123 | 0.2157009 | 116.72732 | 6.6704512 | 0.8032683 | 1.0       | 0.5       | 0.4657545 |
| 16        | 0.8318415 | 0.1741297 | 116.74816 | 5.4126058 | 2.7115490 | 1.0       | 0.5       | 0.4725272 |
| 17        | 0.8205484 | 0.0721251 | 117.63142 | 6.8339515 | 1.2931016 | 1.0       | 0.5       | 2.7761827 |
| 18        | 0.8183139 | 0.1771192 | 718.64189 | 6.3467248 | 0.6314635 | 0.9266712 | 0.6750890 | 3.7336098 |
| 19        | 0.8329968 | 0.5       | 115.17001 | 6.6732260 | 1.9228387 | 0.5       | 0.5       | 0.0       |
| 20        | 0.8307116 | 0.5       | 116.38250 | 4.6794838 | 0.3823097 | 0.5       | 1.0       | 0.0       |
| 21        | 0.8318288 | 0.1277904 | 715.36383 | 10.0      | 0.0       | 0.7121685 | 1.0       | 3.7478913 |
| 22        | 0.8340823 | 0.2551070 | 717.08173 | 10.0      | 0.0       | 0.9351936 | 1.0       | 1.0492380 |
| 23        | 0.8295753 | 0.01      | 716.82240 | 10.0      | 2.8088809 | 0.5       | 1.0       | 2.2727517 |
| 24        | 0.8250682 | 0.5       | 713.90082 | 9.4837677 | 0.0       | 1.0       | 1.0       | 0.0089042 |
| 25        | 0.8374722 | 0.01      | 112.05307 | 5.8467419 | 0.0       | 1.0       | 0.5       | 0.0       |
| 26        | 0.8250745 | 0.5       | 111.60542 | 8.5767716 | 0.0       | 1.0       | 0.5       | 0.0       |
| 27        | 0.8126706 | 0.01      | 112.05753 | 3.6770427 | 1.3999705 | 1.0       | 0.5       | 0.0       |
| 28        | 0.8419983 | 0.01      | 113.82657 | 6.5317722 | 0.0       | 1.0       | 0.7924265 | 0.0       |
| 29        | 0.8318352 | 0.01      | 113.31307 | 6.4956875 | 0.0       | 0.9981812 | 1.0       | 1.6589406 |
| 30        | 0.8205675 | 0.5       | 719.62282 | 10.0      | 0.0       | 0.5       | 1.0       | 1.6869319 |
| 31        | 0.8318352 | 0.01      | 114.82232 | 7.8667576 | 0.0       | 0.5       | 0.8516637 | 0.0       |
| 32        | 0.8081317 | 0.5       | 716.83394 | 10.0      | 1.7735036 | 1.0       | 0.5       | 5.0       |
| 33        | 0.8363486 | 0.01      | 113.10297 | 6.7942951 | 1.0791006 | 1.0       | 0.5       | 0.0       |
| 34        | 0.8374722 | 0.01      | 114.33814 | 5.3650349 | 0.0       | 1.0       | 0.5       | 0.0       |
| 35        | 0.8397130 | 0.01      | 716.06437 | 8.3425655 | 0.0       | 0.5       | 1.0       | 2.1309204 |
| 36        | 0.8318415 | 0.01      | 716.42920 | 7.8583658 | 1.5497814 | 0.5       | 1.0       | 0.5643440 |
| 37        | 0.8295689 | 0.01      | 714.21427 | 7.1974763 | 0.0       | 0.5       | 1.0       | 3.0472623 |
| 38        | 0.8194312 | 0.01      | 715.55166 | 10.0      | 5.2641779 | 0.5       | 1.0       | 0.0       |
| 39        | 0.8171776 | 0.2739275 | 810.37673 | 3.6442509 | 8.3360897 | 0.6892689 | 0.5971490 | 1.2705873 |
| 40        | 0.8307179 | 0.1990157 | 810.03718 | 3.7621348 | 0.9569291 | 0.9341653 | 0.6719009 | 1.5946543 |
| 41        | 0.8340950 | 0.0326570 | 812.92861 | 3.4143269 | 2.1353344 | 0.7735450 | 0.8673299 | 0.3285190 |
| 42        | 0.8194248 | 0.3665239 | 812.97382 | 4.1330369 | 2.2258886 | 1.0       | 0.5034382 | 2.9910557 |
| 43        | 0.8374849 | 0.01      | 812.02538 | 3.0       | 0.0       | 0.5       | 1.0       | 0.0       |
| 44        | 0.8386085 | 0.01      | 812.13991 | 5.3109506 | 0.0       | 0.5       | 1.0       | 0.0       |
| 45        | 0.8386021 | 0.01      | 814.29140 | 4.2842805 | 0.0       | 0.5       | 1.0       | 0.0       |
| 46        | 0.8374785 | 0.01      | 814.33730 | 6.9678319 | 0.0       | 0.5       | 1.0       | 0.0       |
| 47        | 0.8318479 | 0.01      | 812.61059 | 7.1158899 | 2.1851062 | 0.5       | 1.0       | 0.0       |
| 48        | 0.8386085 | 0.01      | 817.02381 | 5.6973376 | 0.0       | 0.5       | 1.0       | 0.0       |
| 49        | 0.8318479 | 0.01      | 816.26766 | 5.8209203 | 2.4074964 | 0.5       | 1.0       | 0.0       |
| 50        | 0.8284390 | 0.5       | 817.23116 | 3.0       | 0.0       | 1.0       | 1.0       | 0.0       |
| 51        | 0.8363422 | 0.01      | 817.35342 | 8.4169641 | 0.0       | 0.5       | 1.0       | 0.0       |
| 52        | 0.8363295 | 0.01      | 816.68904 | 6.9542427 | 0.0       | 0.5       | 1.0       | 2.3757766 |
| 53        | 0.8374722 | 0.01      | 819.73070 | 6.7479329 | 0.0       | 0.5       | 0.5       | 1.1911294 |
| 54        | 0.8307116 | 0.5       | 819.43799 | 9.2707178 | 0.0       | 1.0       | 1.0       | 2.9017608 |
| 55        | 0.8318542 | 0.01      | 820.12695 | 7.6207072 | 2.5004938 | 0.5       | 1.0       | 0.0       |
| 56        | 0.8295753 | 0.01      | 819.66922 | 5.0067896 | 0.0       | 0.5       | 1.0       | 3.7496292 |
| 57        | 0.8374531 | 0.01      | 814.61184 | 10.0      | 0.0       | 0.5       | 0.5       | 1.9127920 |
| 58        | 0.8329778 | 0.01      | 812.04821 | 10.0      | 0.0       | 0.5       | 0.5       | 0.0       |
| 59        | 0.8273217 | 0.01      | 816.02553 | 10.0      | 2.6490218 | 0.5       | 0.5       | 1.5624433 |
| 60        | 0.8228020 | 0.01      | 812.44719 | 9.9680741 | 0.0       | 0.5       | 1.0       | 3.9864114 |
| 61        | 0.8363549 | 0.01      | 822.51053 | 5.7890592 | 0.0       | 0.5       | 0.5       | 0.0       |
| 62        | 0.8352313 | 0.01      | 822.56638 | 8.8634367 | 0.0       | 0.5       | 0.5       | 0.0       |
| 63        | 0.8295753 | 0.01      | 823.92148 | 7.1160793 | 0.0       | 0.5       | 0.5       | 2.6022452 |
| 64        | 0.8081698 | 0.5       | 824.09384 | 6.3849295 | 2.9374955 | 1.0       | 0.5       | 0.0       |
| 65        | 0.8374785 | 0.01      | 809.01110 | 6.7916824 | 0.0       | 0.5       | 1.0       | 0.0       |
| 66        | 0.8386021 | 0.01      | 806.41489 | 5.0879304 | 0.0       | 0.5       | 1.0       | 0.0       |
| 67        | 0.8329841 | 0.01      | 806.81005 | 6.5815329 | 2.4100438 | 0.5       | 1.0       | 0.0       |
| 68        | 0.8250745 | 0.5       | 806.29458 | 6.6253226 | 0.0       | 0.5       | 0.5       | 2.3052786 |
| 69        | 0.8386085 | 0.01      | 807.73869 | 3.0       | 0.0       | 0.5       | 1.0       | 0.0       |
| 70        | 0.8352123 | 0.01      | 805.33643 | 3.0       | 1.7089792 | 1.0       | 1.0       | 0.0       |
| 71        | 0.8374785 | 0.01      | 802.64465 | 4.1084240 | 0.0       | 0.5       | 1.0       | 0.0       |
| 72        | 0.8295880 | 0.01      | 801.53554 | 4.8899277 | 2.9635904 | 0.5       | 1.0       | 0.0       |
| 73        | 0.8182822 | 0.01      | 803.36269 | 3.0       | 0.0       | 1.0       | 1.0       | 2.5865567 |
| 74        | 0.8374785 | 0.01      | 802.72377 | 6.9568570 | 0.0       | 0.5       | 1.0       | 0.0       |
| 75        | 0.8261981 | 0.0861345 | 799.76359 | 6.1504717 | 0.0       | 0.5       | 0.5       | 0.0       |
| 76        | 0.8397448 | 0.01      | 804.02538 | 10.0      | 0.0       | 0.5       | 1.0       | 0.0       |
| 77        | 0.8307179 | 0.01      | 803.06417 | 9.9118383 | 2.4780875 | 0.6618913 | 1.0       | 0.0       |
| 78        | 0.8363422 | 0.01      | 806.72002 | 10.0      | 0.0       | 1.0       | 1.0       | 0.0       |
| 79        | 0.8228210 | 0.5       | 804.88620 | 7.9830015 | 0.0       | 1.0       | 1.0       | 0.0       |
| 80        | 0.8397448 | 0.01      | 801.73784 | 10.0      | 0.0       | 0.5       | 1.0       | 0.0       |
| 81        | 0.8385894 | 0.01      | 802.64662 | 10.0      | 0.0       | 0.5       | 1.0       | 2.1267314 |
| 82        | 0.8374531 | 0.01      | 799.92287 | 10.0      | 0.0       | 0.5       | 1.0       | 2.2907761 |
| 83        | 0.8002412 | 0.01      | 801.09346 | 10.0      | 0.0       | 0.5       | 0.5       | 5.0       |
| 84        | 0.8149431 | 0.5       | 798.97932 | 10.0      | 0.0       | 0.5       | 1.0       | 0.3159515 |
| 85        | 0.8318352 | 0.01      | 808.17308 | 4.6932600 | 1.1998902 | 0.5       | 1.0       | 0.0       |
| 86        | 0.8374722 | 0.01      | 815.46522 | 8.2430133 | 0.0       | 0.5       | 0.5       | 1.1265699 |
| 87        | 0.8363486 | 0.01      | 801.98593 | 8.7773494 | 0.0       | 1.0       | 0.5       | 1.1029225 |
| 88        | 0.8284517 | 0.01      | 809.02536 | 9.1948700 | 1.1007786 | 0.5       | 1.0       | 0.0       |
| 89        | 0.8374658 | 0.01      | 805.70783 | 3.3416736 | 0.0       | 0.5       | 0.5       | 0.0       |
| 90        | 0.8397384 | 0.01      | 820.12891 | 5.0305231 | 0.0       | 0.5       | 1.0       | 0.0       |
| 91        | 0.8216847 | 0.5       | 818.69574 | 6.1553748 | 0.8210701 | 1.0       | 0.5       | 0.0       |
| 92        | 0.8397194 | 0.01      | 821.21242 | 5.2915919 | 0.0       | 0.5       | 1.0       | 1.4040813 |
| 93        | 0.8374722 | 0.01      | 815.43026 | 5.6018162 | 0.0       | 0.5       | 0.5       | 1.1413812 |
| 94        | 0.8363486 | 0.01      | 821.11847 | 7.0464318 | 0.0       | 0.5       | 1.0       | 0.0741556 |
| 95        | 0.8374849 | 0.01      | 821.47278 | 3.4254772 | 0.0       | 0.5       | 1.0       | 0.0726121 |
| 96        | 0.8194248 | 0.5       | 815.04700 | 10.0      | 0.0       | 1.0       | 1.0       | 0.0       |
| 97        | 0.8318288 | 0.01      | 804.20186 | 5.0161094 | 1.0627819 | 0.5       | 0.5       | 0.0       |
| 98        | 0.8182949 | 0.01      | 816.01372 | 9.1729655 | 0.0       | 0.5       | 0.5       | 3.2414503 |
| 99        | 0.8363359 | 0.01      | 820.00894 | 3.7901018 | 0.0       | 0.5       | 1.0       | 1.2980003 |
| 100       | 0.8374849 | 0.01      | 816.12474 | 6.9105214 | 0.0       | 1.0       | 1.0       | 0.4189188 |
| 101       | 0.8397194 | 0.01      | 801.51930 | 10.0      | 1.1610428 | 0.5       | 1.0       | 1.4550740 |
| 102       | 0.8419729 | 0.01      | 813.19849 | 7.6645646 | 0.0       | 0.5       | 0.5       | 1.5427827 |
| 103       | 0.8250491 | 0.5       | 811.48131 | 7.1758877 | 0.0       | 1.0       | 0.5       | 0.8577570 |
| 104       | 0.8397194 | 0.01      | 814.23440 | 6.8651134 | 0.0       | 0.5       | 1.0       | 2.0395676 |
| 105       | 0.8340823 | 0.01      | 813.90675 | 8.2581790 | 1.1931139 | 0.5       | 0.5       | 1.6406764 |
| 106       | 0.8397384 | 0.01      | 820.04291 | 9.5752665 | 0.0       | 0.5       | 1.0       | 0.0       |
| 107       | 0.8374722 | 0.01      | 820.94916 | 10.0      | 1.3716730 | 0.5       | 0.5       | 0.9292984 |
| 108       | 0.8284707 | 0.01      | 819.11830 | 10.0      | 1.7124729 | 0.5       | 1.0       | 0.0       |
| 109       | 0.8194375 | 0.2811900 | 609.86475 | 9.8322347 | 1.9128605 | 0.5253385 | 0.6867907 | 0.6864569 |
| 110       | 0.8374658 | 0.01      | 821.10846 | 8.6900775 | 0.0       | 0.5       | 1.0       | 1.5391549 |
=============================================================================================================

In [7]:
import sys
!{sys.executable} -m pip install bayesian-optimization

Collecting bayesian-optimization
  Using cached bayesian_optimization-3.1.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: colorama>=0.4.6 in /opt/anaconda3/lib/python3.13/site-packages (from bayesian-optimization) (0.4.6)
Requirement already satisfied: numpy>=2.1.3 in /opt/anaconda3/lib/python3.13/site-packages (from bayesian-optimization) (2.1.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from bayesian-optimization) (1.6.1)
Requirement already satisfied: scipy>=1.14.1 in /opt/anaconda3/lib/python3.13/site-packages (from bayesian-optimization) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.0.0->bayesian-optimization) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.0.0->bayesian-optimization) (3.5.0)
Using cached bayesian_optimization-3.1.0-py3-none-any.whl (36 kB)
Installing collected packages: bayesian-optimization
Successfully installed bayesian-optimization-3.1.0

In [10]:
optimizer.max

{'target': np.float64(0.8419983495207262),
 'params': {'learning_rate': np.float64(0.01),
  'n_estimators': np.float64(113.82657767044938),
  'max_depth': np.float64(6.5317722366886395),
  'min_child_weight': np.float64(0.0),
  'subsample': np.float64(1.0),
  'colsample_bytree': np.float64(0.7924265863656789),
  'gamma': np.float64(0.0)}}

In [11]:
learning_rate = [0.001, 0.005, 0.01, 0.05, 0.06, 0.1, 0.12, 0.15, 0.17, 0.2]
n_estimators = [10, 50, 60, 75, 85, 100, 125, 150, 200, 250, 500, 1000]

hyperparams = {
    "learning_rate": learning_rate,
    "n_estimators": n_estimators
}

gd = GridSearchCV(
    estimator = XGBClassifier(random_state=1, eval_metric="logloss"),
    param_grid = hyperparams,
    verbose = True,
    cv = 5,
    scoring = "accuracy",
    n_jobs = -1
)

gd.fit(train_importance, train_answer)
print(gd.best_score_)
print(gd.best_params_)

Fitting 5 folds for each of 120 candidates, totalling 600 fits
0.83747222751222
{'learning_rate': 0.17, 'n_estimators': 10}

In [12]:
max_depth = [3, 4, 5, 6, 7, 8, 9, 10]
min_child_weight = [1, 2, 3, 4, 5, 6, 7]

hyperparams = {
    "max_depth": max_depth,
    "min_child_weight": min_child_weight
}

gd = GridSearchCV(
    estimator=XGBClassifier(learning_rate=0.17, n_estimators=10, random_state=1, eval_metric="logloss"),
    param_grid=hyperparams,
    verbose=True,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

gd.fit(train_importance, train_answer)
print(gd.best_score_)
print(gd.best_params_)

Fitting 5 folds for each of 56 candidates, totalling 280 fits
0.83747222751222
{'max_depth': 6, 'min_child_weight': 1}

In [13]:
gamma=[i * 0.1 for i in range(0, 5)] # 표준 손실 감소량 => 1에 가까울 수록 노드를 쪼개는데 비해서 그만큼 현격한 결과가 도출될 때에만 쪼개라.
subsample=[0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1] # 학습시키고자 하는 데이터의 전체 행을 기준으로 몇 프로
colsample_bytree=[0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1] # 학습시키고자 하는 데이터의 전체 열을 기준으로 몇 프로
reg_alpha=[1e-5, 1e-2, 0.1, 1, 100] # 학습시키고자 하는 데이터의 결과값 너무 작은, 큰 값에 치우지지 않게 하기 위한 옵션

hyerparams={
    "gamma": gamma,
    "subsample": subsample,
    "colsample_bytree": colsample_bytree,
    "reg_alpha": reg_alpha
}

gd=GridSearchCV(
    estimator=XGBClassifier(
        learning_rate=0.17,
        n_estimators=10,
        max_depth=6,
        min_child_weight=1,
        random_state=1,
        eval_metric="logloss"
    ),
    param_grid=hyerparams,
    verbose=True,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

gd.fit(train_importance, train_answer)
print(gd.best_score_)
print(gd.best_params_)

Fitting 5 folds for each of 2025 candidates, totalling 10125 fits
0.8476163270488162
{'colsample_bytree': 0.85, 'gamma': 0.2, 'reg_alpha': 1e-05, 'subsample': 1}

In [16]:
# RandomForest

In [15]:
n_estimators = [10, 50, 100, 200]
max_depth = [3, None]
max_features = [0.1, 0.2, 0.5, 0.8, "sqrt", "log2"]
min_samples_split = [2, 4, 6, 8, 10] # 의사결정 트리에서 분기해도되는지에 대한 여부 => 최소값
min_samples_leaf = [2, 4, 6, 8, 10] # 의사결정 트리로 분기가 된 이후에 만들어지는 노드 값의 최소값

hyerparams={
    "n_estimators": n_estimators,
    "max_depth": max_depth,
    "max_features": max_features,
    "min_samples_split": min_samples_split,
    "min_samples_leaf": min_samples_leaf
}

gd = GridSearchCV(
    estimator=RandomForestClassifier(random_state=1),
    param_grid=hyerparams,
    verbose=True,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

gd.fit(train_importance, train_answer.values.ravel())
print(gd.best_score_)
print(gd.best_params_)

Fitting 5 folds for each of 1200 candidates, totalling 6000 fits
0.8487526185488479
{'max_depth': None, 'max_features': 0.8, 'min_samples_leaf': 2, 'min_samples_split': 8, 'n_estimators': 200}

In [17]:
# Extra Trees

In [18]:
n_estimators=[10, 50, 100, 200]
max_depth=[3, None]
max_features = [0.1, 0.2, 0.5, 0.8, "sqrt", "log2"]
min_samples_split = [2, 4, 6, 8, 10] # 의사결정 트리에서 분기해도되는지에 대한 여부 => 최소값
min_samples_leaf = [2, 4, 6, 8, 10] # 의사결정 트리로 분기가 된 이후에 만들어지는 노드 값의 최소값

hyerparams={
    "n_estimators": n_estimators,
    "max_depth": max_depth,
    "max_features": max_features,
    "min_samples_split": min_samples_split,
    "min_samples_leaf": min_samples_leaf
}

gd = GridSearchCV(
    estimator=ExtraTreesClassifier(random_state=1),
    param_grid=hyerparams,
    verbose=True,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

gd.fit(train_importance, train_answer.values.ravel())
print(gd.best_score_)
print(gd.best_params_)

Fitting 5 folds for each of 1200 candidates, totalling 6000 fits
0.8532787405573542
{'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 8, 'n_estimators': 10}

In [21]:
logreg_model = LogisticRegression(C=706, penalty="l2", random_state=1)

xgb_model = XGBClassifier(
    eval_metric = "logloss",
    learning_rate = 0.01,
    n_estimators = 113,
    max_depth = 6,
    min_child_weight = 0.0,
    gamma = 0.0,
    random_state = 1
)

random_model = RandomForestClassifier(
    max_depth = None,
    max_features = 0.8,
    min_samples_leaf = 2,
    min_samples_split = 8,
    n_estimators = 200,
    random_state = 1
)

extra_model = ExtraTreesClassifier(
    max_depth = None,
    max_features = 'sqrt',
    min_samples_leaf = 2,
    min_samples_split = 8,
    n_estimators = 10,
    random_state = 1
)

In [22]:
from sklearn.ensemble import VotingClassifier

grid_hard = VotingClassifier(
    estimators=[
        ("Logistic Regression", logreg_model),
        ("XGBoost", xgb_model),
        ("Random Forest", random_model),
        ("Extra Trees", extra_model),
    ], voting="hard"
)

score = cross_val_score(grid_hard, train_importance, train_answer, cv=5, scoring="accuracy")
print(np.mean(score) * 100)

85.55386275630038

In [23]:
from sklearn.ensemble import VotingClassifier

grid_soft = VotingClassifier(
    estimators=[
        ("Logistic Regression", logreg_model),
        ("XGBoost", xgb_model),
        ("Random Forest", random_model),
        ("Extra Trees", extra_model),
    ], voting="soft"
)

score = cross_val_score(grid_soft, train_importance, train_answer, cv=5, scoring="accuracy")
print(np.mean(score) * 100)

84.08557100234877

In [26]:
test = pd.read_csv("titanic/test.csv")
submission = pd.DataFrame(columns=["PassengerId", "Survived"])
submission["PassengerId"] = test["PassengerId"]

In [27]:
submission

     PassengerId Survived
0            892      NaN
1            893      NaN
2            894      NaN
3            895      NaN
4            896      NaN
..           ...      ...
413         1305      NaN
414         1306      NaN
415         1307      NaN
416         1308      NaN
417         1309      NaN

[418 rows x 2 columns]

In [28]:
grid_hard.fit(train_importance, train_answer)

VotingClassifier(estimators=[('Logistic Regression',
                              LogisticRegression(C=706, random_state=1)),
                             ('XGBoost',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric='logloss',
                                            feature_types=None,
                                            feature_weights=...
                                            min_child_weight=0.0, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=113, n_jobs=None,
                                            num_parallel_tree=None, ...)),
                             ('Random Forest',
                              RandomForestClassifier(max_features=0.8,
                                                     min_samples_leaf=2,
                                                     min_samples_split=8,
                                                     n_estimators=200,
                                                     random_state=1)),
                             ('Extra Trees',
                              ExtraTreesClassifier(min_samples_leaf=2,
                                                   min_samples_split=8,
                                                   n_estimators=10,
                                                   random_state=1))])

In [29]:
submission["Survived"]=grid_hard.predict(test_importance)
submission = submission.astype("int")
submission.head()

ValueError: Length of values (416) does not match length of index (418)

In [30]:
len(submission)

418

In [31]:
len(test_importance)

416

In [33]:
test_importance

,Initial_0,Pclass_2,Sex_0,Sex_1,Cabin_0,Initial_6,Fare_0,LowChance_0,HighChance_0,LowChance_1,...,Age_6,Family_0,Ticket_Num_Cut_3,Fare_3,Cabin_4,Ticket_Initial2_2,Cabin_1,Age_1,Ticket_Initial2_15,Family_4
0,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
1,0,1,0,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,1,0,1,0,1,1,...,1,1,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
4,0,1,0,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,0,1,0,1,1,0,1,1,1,0,...,0,1,0,0,0,0,0,0,0,0
413,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
415,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
416,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
417,0,1,1,0,1,0,0,1,1,0,...,0,0,0,0,0,0,0,1,0,0

In [32]:
submission

     PassengerId Survived
0            892      NaN
1            893      NaN
2            894      NaN
3            895      NaN
4            896      NaN
..           ...      ...
413         1305      NaN
414         1306      NaN
415         1307      NaN
416         1308      NaN
417         1309      NaN

[418 rows x 2 columns]

In [34]:
submission = submission.loc[test_importance.index]
submission["Survived"] = grid_hard.predict(test_importance)
submission = submission.astype("int")

In [35]:
submission.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [36]:
submission.to_csv("titanic_predict.csv", header=True, index=False)

In [37]:
import os
os.environ["KAGGLE_API_TOKEN"] = ""

!kaggle competitions list

/Users/admin/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
ref                                                                                 deadline             category                reward  teamCount  userHasEntered
----------------------------------------------------------------------------------  -------------------  ---------------  -------------  ---------  --------------
https://www.kaggle.com/competitions/ai-mathematical-olympiad-progress-prize-3       2026-04-15 23:59:00  Featured         2,207,152 Usd       1032           False
https://www.kaggle.com/competitions/vesuvius-challenge-surface-detection            2026-02-13 23:59:00  Research           200,000 Usd        476           False
https://www.kaggle.com/competitions/google-tunix-hackathon                          2026-01-12 23:59:00  Featured           100,000 Usd        102           False
https://www.kaggle.com/competitions/csiro-biomass                                   2026-01-28 23:59:00  Research            75,000 Usd       2678           False
https://www.kaggle.com/competitions/recodai-luc-scientific-image-forgery-detection  2026-01-15 23:59:00  Research            55,000 Usd       1140           False
https://www.kaggle.com/competitions/santa-2025                                      2026-01-30 23:59:00  Featured            50,000 Usd       2346           False
https://www.kaggle.com/competitions/cafa-6-protein-function-prediction              2026-02-02 23:59:00  Research            50,000 Usd       1420           False
https://www.kaggle.com/competitions/physionet-ecg-image-digitization                2026-01-22 23:59:00  Research            50,000 Usd        880           False
https://www.kaggle.com/competitions/deep-past-initiative-machine-translation        2026-03-23 23:59:00  Featured            50,000 Usd        674           False
https://www.kaggle.com/competitions/playground-series-s5e12                         2025-12-31 23:59:00  Playground                Swag       3735           False
https://www.kaggle.com/competitions/titanic                                         2030-01-01 00:00:00  Getting Started      Knowledge      15700           False
https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques     2030-01-01 00:00:00  Getting Started      Knowledge       5804           False
https://www.kaggle.com/competitions/home-data-for-ml-course                         2030-01-01 23:59:00  Getting Started      Knowledge       4660           False
https://www.kaggle.com/competitions/spaceship-titanic                               2030-01-01 00:00:00  Getting Started      Knowledge       2700           False
https://www.kaggle.com/competitions/digit-recognizer                                2030-01-01 00:00:00  Getting Started      Knowledge       1397           False
https://www.kaggle.com/competitions/nlp-getting-started                             2030-01-01 00:00:00  Getting Started      Knowledge        745           False
https://www.kaggle.com/competitions/store-sales-time-series-forecasting             2030-06-30 23:59:00  Getting Started      Knowledge        716           False
https://www.kaggle.com/competitions/tpu-getting-started                             2030-06-03 23:59:00  Getting Started      Knowledge        358           False
https://www.kaggle.com/competitions/llm-classification-finetuning                   2030-07-01 23:59:00  Getting Started      Knowledge        297           False
https://www.kaggle.com/competitions/connectx                                        2030-01-01 00:00:00  Getting Started      Knowledge        247           False

In [38]:
!kaggle competitions submit -c titanic -f titanic_predict.csv -m "Test"

/Users/admin/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
100%|██████████████████████████████████████| 2.76k/2.76k [00:00<00:00, 3.09kB/s]
Successfully submitted to Titanic - Machine Learning from Disaster

In [ ]:
kaggle competitions submit -c titanic -f submission.csv -m "Message"

In [39]:
test_ids = set(test["PassengerId"])

In [41]:
test_importance

,Initial_0,Pclass_2,Sex_0,Sex_1,Cabin_0,Initial_6,Fare_0,LowChance_0,HighChance_0,LowChance_1,...,Age_6,Family_0,Ticket_Num_Cut_3,Fare_3,Cabin_4,Ticket_Initial2_2,Cabin_1,Age_1,Ticket_Initial2_15,Family_4
0,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
1,0,1,0,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,1,0,1,0,1,1,...,1,1,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
4,0,1,0,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,0,1,0,1,1,0,1,1,1,0,...,0,1,0,0,0,0,0,0,0,0
413,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
415,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
416,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0
417,0,1,1,0,1,0,0,1,1,0,...,0,0,0,0,0,0,0,1,0,0

In [40]:
mp_ids = set(test_importance["PassengerId"])

KeyError: 'PassengerId'

In [42]:
missing_idx = test.index.difference(test_importance.index)
missing_idx, len(missing_idx)

(Index([88, 414], dtype='int64'), 2)

In [43]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": 0
}, index=test.index)

pred = grid_hard.predict(test_importance)

submission.loc[test_importance.index, "Survived"] = pred
submission["Survived"] = submission["Survived"].astype(int)

len(submission), submission["Survived"].isna().sum()

(418, np.int64(0))

In [48]:
submission.to_csv("titanic_predict.csv", header=True, index=False)

In [49]:
len(submission)

418

In [50]:
!kaggle competitions submit -c titanic -f titanic_predict.csv -m "Test"

/Users/admin/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
100%|██████████████████████████████████████| 2.77k/2.77k [00:00<00:00, 2.93kB/s]
Successfully submitted to Titanic - Machine Learning from Disaster