In [12]:
import pickle

with open("titanic_step2_feature_add.pickle", "rb") as pickle_filename :
    df = pickle.load(pickle_filename)

In [ ]:
# 인코딩 => 특정 사이트 데이터 크롤링 => 주피터노트북 (*문자열 깨짐없이) | 코드문안 => 컴퓨터 이해할 수 있는 형태
# 사람이 이해할 수 있는 문법 => 컴퓨터 이해할 수 있는 형태 : 인코딩
# 컴퓨터 처리한 문법 => 사람이 이해할 수 있는 형태 : 디코딩

# sklearn & numpy & pandas & plotly
# 레이블 인코딩 => LableEncoding

# 레이블 인코딩 : 문자열 형태의 데이터를 가지고 있다 => 숫자형태의 범주형 카테고리로 분류해서 알아서 인코딩
# 원핫 인코딩 => OneHotEncoding : 각 문자열 범주마다 새로운 feature를 만들고 해당 범주에 속하는 경우에만 1값을 부여하는 방식의 인코딩
# BigQuery => event params => key

In [13]:
df_label = df.copy()
df_onehot = df.copy()

ntrain = 886
train = df[:ntrain]

y_train = train[["Survived"]].copy()

In [14]:
y_train

     Survived
0         0.0
1         1.0
2         1.0
3         1.0
4         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[886 rows x 1 columns]

In [3]:
drop_features = ["PassengerId", "Survived"]
df_label = df_label.drop(drop_features, axis=1).copy()
df_label.head()

,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,3,0,3.0,0.0,0,0,0.0,2,0,3,0,0
1,1,1,4.0,3.0,1,1,2.0,2,1,3,2,0
2,3,1,3.0,0.0,0,0,1.0,1,2,9,0,0
3,1,1,4.0,2.0,1,0,2.0,2,3,5,2,0
4,3,0,4.0,0.0,0,0,0.0,1,3,9,0,2

In [4]:
drop_features = ["PassengerId", "Survived"]
df_onehot = df_onehot.drop(drop_features, axis=1).copy()
df_onehot.head()

,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,3,0,3.0,0.0,0,0,0.0,2,0,3,0,0
1,1,1,4.0,3.0,1,1,2.0,2,1,3,2,0
2,3,1,3.0,0.0,0,0,1.0,1,2,9,0,0
3,1,1,4.0,2.0,1,0,2.0,2,3,5,2,0
4,3,0,4.0,0.0,0,0,0.0,1,3,9,0,2

In [5]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [6]:
df_label = df_label.apply(LabelEncoder().fit_transform)

In [7]:
df_label.head()

,Pclass,Sex,Age,Fare,Cabin,Embarked,Initial,Family,Ticket_Initial2,Ticket_Num_Cut,HighChance,LowChance
0,2,0,3,0,0,0,0,1,0,3,0,0
1,0,1,4,3,1,1,2,1,1,3,2,0
2,2,1,3,0,0,0,1,0,2,9,0,0
3,0,1,4,2,1,0,2,1,3,5,2,0
4,2,0,4,0,0,0,0,0,3,9,0,2

In [11]:
import pandas as pd

onehot_cols = df_label.columns.tolist()
df_onehot = pd.get_dummies(df_label, columns=onehot_cols)
df_onehot = df_onehot.astype(int)

df_onehot.head()

,Pclass_0,Pclass_1,Pclass_2,Sex_0,Sex_1,Age_0,Age_1,Age_2,Age_3,Age_4,...,HighChance_0,HighChance_1,HighChance_2,HighChance_3,HighChance_4,HighChance_5,HighChance_6,LowChance_0,LowChance_1,LowChance_2
0,0,0,1,1,0,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
1,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
2,0,0,1,0,1,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
4,0,0,1,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,1

In [9]:
onehot_cols

['Pclass',
 'Sex',
 'Age',
 'Fare',
 'Cabin',
 'Embarked',
 'Initial',
 'Family',
 'Ticket_Initial2',
 'Ticket_Num_Cut',
 'HighChance',
 'LowChance']

In [13]:
import pickle

with open("titanic_step3_feature_encoding.pickle", "wb") as pickle_filename :
    pickle.dump(df_onehot, pickle_filename)

In [14]:
import pickle

with open("titanic_step3_feature_encoding_y.pickle", "wb") as pickle_filename :
    pickle.dump(y_train, pickle_filename)

In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

# 몇개 등분으로 나눌것인가, 등분으로 나눈 구간에 데이터의 값을 섞어서 넣을지, 랜덤형태로 섞을것인지
# n_splits, shuffle, randim_state
# 컴퓨터는 랜덤기능 > 랜덤 > 애초에 컴퓨터는 숫자를 랜덤으로 추첨 x
# 0, 1 => 최초의 랜덤 => 계속 // 랜덤 x // 랜덤씨드 => 시간

# 어떤 모델, 어떤 데이터값, 어떤 설정, 어떤 계산식으로 교차검증을 할 것인가?
# estimator : 어떤 모델을 사용할 것인가?
# x : train 시킬 데이터 값
# y : train 시킬 데이터의 정답
# cv : forld 객체를 통해서 생성된 인스턴스 객체
# n_jobs : cpu 1
# scoring : 모델 평가식을 어떻게 할 것인지

knn = KNeighborsClassifier(n_neighbors=13)
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)
score = cross_val_score(knn, X_train, y_train, cv=k_fold, n_jobs=1, scoring="accuracy")

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pickle
with open("titanic_step3_feature_encoding.pickle", "rb") as pickle_filename :
    df_oneshot = pickle.load(pickle_filename)

with open("titanic_step3_feature_encoding_y.pickle", "rb") as pickle_filename :
    y_train = pickle.load(pickle_filename)

ntrain = 886
X_train, X_test = df_oneshot[:ntrain], df_oneshot[ntrain:]
X_train.head()

   Pclass_0  Pclass_1  Pclass_2  ...  LowChance_0  LowChance_1  LowChance_2
0         0         0         1  ...            1            0            0
1         1         0         0  ...            1            0            0
2         0         0         1  ...            1            0            0
3         1         0         0  ...            1            0            0
4         0         0         1  ...            0            0            1

[5 rows x 92 columns]

In [2]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [3]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=13)
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

In [4]:
score = cross_val_score(knn, X_train, y_train, cv=k_fold, n_jobs=1, scoring="accuracy")
score

array([0.86516854, 0.78651685, 0.80898876, 0.82022472, 0.82022472,
       0.79775281, 0.85227273, 0.78409091, 0.86363636, 0.86363636])

In [5]:
import numpy as np
np.mean(score) * 100

np.float64(82.62512768130745)

In [9]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold

iris_data = load_iris()

In [7]:
dir(iris_data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [10]:
iris_df = pd.DataFrame(data = iris_data.data, columns = iris_data.feature_names)

In [11]:
iris_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
iris_df["species"] = iris_data.target

In [14]:
iris_df["species"].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [15]:
skfold = StratifiedKFold(n_splits=3)

for train_index, test_index in skfold.split(iris_df, iris_df["species"]) :
    trainset = iris_df["species"].iloc[train_index]
    testset = iris_df["species"].iloc[test_index]
    print("train set", trainset.value_counts())
    print("test set", testset.value_counts())

train set species
2    34
0    33
1    33
Name: count, dtype: int64
test set species
0    17
1    17
2    16
Name: count, dtype: int64
train set species
1    34
0    33
2    33
Name: count, dtype: int64
test set species
0    17
2    17
1    16
Name: count, dtype: int64
train set species
0    34
1    33
2    33
Name: count, dtype: int64
test set species
1    17
2    17
0    16
Name: count, dtype: int64

In [16]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_predict

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=13)
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

In [15]:
import warnings
warnings.filterwarnings("ignore")

import pickle
with open("titanic_step3_feature_encoding.pickle", "rb") as pickle_filename :
    df_oneshot = pickle.load(pickle_filename)

with open("titanic_step3_feature_encoding_y.pickle", "rb") as pickle_filename :
    y_train = pickle.load(pickle_filename)

ntrain = 886
X_train, X_test = df_oneshot[:ntrain], df_oneshot[ntrain:]
X_train.head()

,Pclass_0,Pclass_1,Pclass_2,Sex_0,Sex_1,Age_0,Age_1,Age_2,Age_3,Age_4,...,HighChance_0,HighChance_1,HighChance_2,HighChance_3,HighChance_4,HighChance_5,HighChance_6,LowChance_0,LowChance_1,LowChance_2
0,0,0,1,1,0,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
1,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
2,0,0,1,0,1,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
4,0,0,1,1,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,1

In [2]:
!pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lightgbm in /Users/admin/Library/Python/3.9/lib/python/site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from lightgbm) (2.0.2)
Requirement already satisfied: scipy in /Users/admin/Library/Python/3.9/lib/python/site-packages (from lightgbm) (1.13.1)

In [3]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in /Users/admin/Library/Python/3.9/lib/python/site-packages (2.1.4)
Requirement already satisfied: numpy in /Users/admin/Library/Python/3.9/lib/python/site-packages (from xgboost) (2.0.2)
Requirement already satisfied: scipy in /Users/admin/Library/Python/3.9/lib/python/site-packages (from xgboost) (1.13.1)

In [10]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

머신러닝 모델링 사용해야하는 함수

1. fit() : 모델에 데이터를 학습, 최적화 시키는 함수

2. predict() : 학습된 모델을 활용해서 새로운 데이터에 대한 값을 예측

3. score() : 모델의 예측성능을 평가

4. cross_val_score() : 모델 성능을 검증하고자 할 때 사용하는 함수

In [7]:
import sys
print(sys.executable)
print(sys.version)

/opt/anaconda3/bin/python
3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 11:23:37) [Clang 14.0.6 ]

In [8]:
import site
print(site.getsitepackages() if hasattr(site, "getsitepackages") else "no getsitepackages")
print(site.getusersitepackages())

['/opt/anaconda3/lib/python3.13/site-packages']
/Users/admin/.local/lib/python3.13/site-packages

In [9]:
import sys
!{sys.executable} -m pip install -U xgboost lightgbm

Collecting xgboost
  Downloading xgboost-3.1.2-py3-none-macosx_12_0_arm64.whl.metadata (2.1 kB)
Collecting lightgbm
  Using cached lightgbm-4.6.0-py3-none-macosx_12_0_arm64.whl.metadata (17 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.1.2-py3-none-macosx_12_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 28.3 MB/s eta 0:00:00
Using cached lightgbm-4.6.0-py3-none-macosx_12_0_arm64.whl (1.6 MB)
Installing collected packages: xgboost, lightgbm
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [lightgbm]━━ 1/2 [lightgbm]
Successfully installed lightgbm-4.6.0 xgboost-3.1.2

In [11]:
logreg_model = LogisticRegression()
svc_model = SVC()
decision_model = DecisionTreeClassifier()
random_model = RandomForestClassifier()
extra_model = ExtraTreesClassifier()
gbm_model = GradientBoostingClassifier()
nb_model = GaussianNB()
xgb_model = XGBClassifier(eval_metric="logloss")
lgbm_model = LGBMClassifier()

results = dict()

In [16]:
alg = logreg_model
alg.fit(X_train, y_train)
train_accuracy = alg.score(X_train, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [17]:
alg = svc_model
alg.fit(X_train, y_train)
train_accuracy = alg.score(X_train, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [18]:
alg = decision_model
alg.fit(X_train, y_train)
train_accuracy = alg.score(X_train, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [19]:
alg = random_model
alg.fit(X_train, y_train)
train_accuracy = alg.score(X_train, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [20]:
alg = extra_model
alg.fit(X_train, y_train)
train_accuracy = alg.score(X_train, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [21]:
alg = gbm_model
alg.fit(X_train, y_train)
train_accuracy = alg.score(X_train, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [22]:
alg = nb_model
alg.fit(X_train, y_train)
train_accuracy = alg.score(X_train, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [23]:
alg = xgb_model
alg.fit(X_train, y_train)
train_accuracy = alg.score(X_train, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [24]:
sorted(results.items(), key=lambda x: x[1], reverse=True)

[('DecisionTreeClassifier', 95.03386004514672),
 ('RandomForestClassifier', 95.03386004514672),
 ('ExtraTreesClassifier', 95.03386004514672),
 ('XGBClassifier', 93.67945823927766),
 ('GradientBoostingClassifier', 88.60045146726863),
 ('LogisticRegression', 86.11738148984199),
 ('SVC', 86.11738148984199),
 ('GaussianNB', 72.12189616252822)]

In [25]:
tree_models = [
    decision_model,
    random_model,
    extra_model,
    xgb_model,
    gbm_model
]

In [28]:
for alg in tree_models :
    try :
        print(alg.__class__.__name__)
        print(alg.feature_importances_)
    except :
        print(alg.__class__.__name__, "X")

DecisionTreeClassifier
[0.00071322 0.         0.08838408 0.         0.00515208 0.
 0.0016758  0.0199666  0.00387364 0.01451006 0.01561498 0.00763251
 0.00392788 0.03970688 0.011159   0.00909252 0.0090091  0.00300303
 0.         0.03804451 0.008431   0.00968438 0.         0.00553653
 0.00771585 0.00281534 0.         0.         0.00170382 0.01350684
 0.01528544 0.34973984 0.00591222 0.00800809 0.01236847 0.
 0.         0.00982562 0.         0.00140767 0.         0.
 0.00499469 0.         0.0018769  0.01317237 0.02188377 0.01796705
 0.         0.00375379 0.00326553 0.         0.         0.00089634
 0.00300303 0.0060146  0.01461528 0.00233155 0.         0.
 0.         0.00734712 0.00573897 0.         0.00102339 0.
 0.00428229 0.00360942 0.0059584  0.         0.         0.
 0.01955502 0.00199358 0.02063766 0.00684097 0.00163302 0.00890112
 0.01500856 0.0086121  0.00845129 0.0091746  0.00688821 0.
 0.         0.         0.         0.         0.         0.00690308
 0.03859866 0.00166059]
RandomForestClassifier
[1.73879099e-02 1.68948194e-02 3.30625701e-02 6.71775040e-02
 7.69322538e-02 4.73582022e-03 9.97875053e-03 1.31747914e-02
 2.20241995e-02 1.67512286e-02 1.57782629e-02 5.10770679e-03
 1.88899778e-03 1.96002389e-02 1.89351122e-02 1.18315925e-02
 5.24634774e-03 2.71945980e-03 5.49259218e-03 2.47821272e-02
 8.28614273e-03 1.10621011e-02 1.68196565e-03 8.17619182e-03
 3.48825874e-03 6.67139553e-03 1.93055829e-03 2.54726271e-04
 1.88573340e-02 1.31055360e-02 9.65341993e-03 7.31096556e-02
 2.35399416e-02 2.28600272e-02 9.20349571e-03 5.19511418e-05
 4.31151369e-04 1.60345152e-03 1.96670202e-03 1.02129190e-03
 4.51400910e-04 1.10078604e-03 1.99823322e-04 1.26980028e-04
 1.61762552e-02 1.45783709e-02 1.49968494e-02 7.27130977e-03
 5.13736953e-03 9.68866353e-03 3.22224277e-03 2.66829941e-03
 1.44536520e-03 4.98245516e-03 4.92638511e-03 5.86020034e-03
 1.41106881e-02 9.68336136e-04 3.38115167e-03 1.59250817e-03
 3.71650522e-04 3.89788778e-03 2.33246049e-03 4.84067427e-04
 3.17386214e-03 8.06012060e-05 1.65169363e-03 8.35680902e-04
 5.03435300e-03 2.31312534e-05 0.00000000e+00 0.00000000e+00
 1.28645843e-02 1.48691071e-02 1.85725478e-02 7.58273167e-03
 1.10595189e-02 1.45646741e-02 1.10836824e-02 1.57741232e-02
 1.74304918e-02 1.22456242e-02 4.02809082e-02 5.09779088e-03
 4.80773973e-03 9.30308932e-03 9.81278946e-04 2.91581550e-05
 8.40683425e-04 3.58026621e-02 7.53521596e-03 2.20459751e-02]
ExtraTreesClassifier
[1.70273612e-02 2.10191310e-02 2.87568036e-02 7.86672114e-02
 6.81716551e-02 5.14988447e-03 9.19324215e-03 1.30352181e-02
 1.98561345e-02 1.66482723e-02 1.59060863e-02 6.31645540e-03
 1.31055631e-03 2.18207026e-02 1.72173630e-02 1.08844573e-02
 5.36820342e-03 2.64799986e-03 7.58440949e-03 2.97006779e-02
 7.04596442e-03 9.42117370e-03 1.43303195e-03 8.41022480e-03
 2.98472805e-03 5.59104007e-03 1.51569682e-03 3.46086764e-04
 1.49100618e-02 1.17598718e-02 8.81525275e-03 9.13071104e-02
 2.38501632e-02 1.50220629e-02 1.17162115e-02 1.94518831e-05
 3.33232274e-04 1.61485758e-03 1.05050280e-03 8.77574394e-04
 4.47514300e-04 5.71044191e-04 3.37602533e-04 5.55047429e-05
 1.54681701e-02 1.43454172e-02 1.57109980e-02 8.28540675e-03
 7.37333482e-03 9.33556563e-03 2.13514100e-03 2.00686135e-03
 1.51586691e-03 5.15754760e-03 5.47629439e-03 4.92877914e-03
 1.52729508e-02 1.17614033e-03 3.54876639e-03 8.60514320e-04
 2.75979824e-04 4.87906234e-03 3.10973630e-03 3.52646741e-04
 3.25396523e-03 6.34002454e-05 2.26131590e-03 1.57195867e-03
 5.02322101e-03 3.57474345e-05 0.00000000e+00 0.00000000e+00
 1.30444013e-02 1.50116455e-02 1.89896686e-02 7.92865745e-03
 1.02083660e-02 1.32908847e-02 1.11008339e-02 1.37899164e-02
 1.50597173e-02 1.32777664e-02 3.82235169e-02 3.19413116e-03
 1.12306631e-02 1.07664659e-02 5.03318358e-04 3.95592050e-05
 1.20103943e-03 2.93457743e-02 9.55656309e-03 1.50945314e-02]
XGBClassifier
[0.00826803 0.00405597 0.07373536 0.03295543 0.         0.0058751
 0.00592263 0.0051344  0.00504774 0.00680214 0.00808481 0.01226474
 0.         0.02450599 0.01154375 0.00946019 0.01130116 0.00381093
 0.00758951 0.03006162 0.00540272 0.00834297 0.         0.00665839
 0.00568981 0.00428444 0.         0.         0.00987185 0.00551451
 0.00706466 0.20554322 0.00589368 0.00561172 0.01259227 0.
 0.         0.12938681 0.         0.         0.         0.
 0.         0.         0.00513496 0.00946858 0.01984451 0.00591799
 0.00683365 0.01877466 0.00402537 0.         0.         0.00730859
 0.00354191 0.00834354 0.00734228 0.         0.00494037 0.00293752
 0.         0.00436808 0.00925901 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.0148011  0.00826066 0.01043449 0.00919239 0.01383906 0.01238711
 0.00690132 0.0059949  0.01422886 0.01186962 0.0235724  0.
 0.         0.00442485 0.         0.         0.         0.05531832
 0.00607546 0.00638191]
GradientBoostingClassifier
[1.50325086e-02 0.00000000e+00 1.12126726e-01 4.22912408e-02
 6.91541023e-02 9.24138994e-04 9.83296861e-04 5.48199710e-04
 4.00274015e-03 7.21446049e-03 1.04493561e-02 8.84671008e-03
 3.74212835e-03 3.41997742e-02 4.92506213e-04 6.34335818e-03
 1.08832618e-03 1.28773036e-04 0.00000000e+00 3.46711384e-02
 8.09216175e-04 1.01663789e-02 1.53391449e-03 2.87292720e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.40234312e-02 8.49316487e-04 1.04879893e-02 3.75466302e-01
 8.60063888e-05 2.54763008e-03 1.42738921e-02 0.00000000e+00
 4.27496782e-04 1.15050925e-02 1.33727745e-03 0.00000000e+00
 5.74914574e-04 0.00000000e+00 3.96688554e-04 1.12461276e-04
 9.39666677e-04 1.30577643e-03 6.85267439e-03 2.72908299e-03
 6.33916478e-03 1.71237887e-02 2.42790338e-04 7.19641412e-03
 3.49238414e-03 2.48455625e-03 1.82470646e-03 5.94120041e-03
 9.81826043e-04 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 4.13147533e-03 1.26909113e-03 0.00000000e+00
 3.42683884e-03 0.00000000e+00 0.00000000e+00 2.77473832e-04
 1.08761144e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.29049024e-02 1.26792818e-03 1.41488130e-02 2.17048698e-03
 8.92049453e-03 2.80962943e-03 2.66206708e-03 4.51845130e-03
 6.65102623e-03 7.43254934e-03 2.60788717e-02 6.19216939e-04
 0.00000000e+00 7.15378301e-04 0.00000000e+00 0.00000000e+00
 0.00000000e+00 7.78898185e-03 2.29678511e-02 1.19790612e-03]

In [29]:
decision_model_importance = pd.DataFrame({"Feature": X_train.columns, "decision_model": decision_model.feature_importances_})
random_model_importance = pd.DataFrame({"Feature": X_train.columns, "random_model": random_model.feature_importances_})
extra_model_importance = pd.DataFrame({"Feature": X_train.columns, "extra_model": extra_model.feature_importances_})
xgb_model_importance = pd.DataFrame({"Feature": X_train.columns, "xgb_model": xgb_model.feature_importances_})
gbm_model_importance = pd.DataFrame({"Feature": X_train.columns, "gbm_model": gbm_model.feature_importances_})

In [31]:
from functools import reduce
data_frames = [
    decision_model_importance,
    random_model_importance,
    extra_model_importance,
    xgb_model_importance,
    gbm_model_importance
]

importances = reduce(lambda left,right: pd.merge(left, right, on=["Feature"]), data_frames)

In [32]:
importances.head()

    Feature  decision_model  random_model  extra_model  xgb_model  gbm_model
0  Pclass_0        0.000713      0.017388     0.017027   0.008268   0.015033
1  Pclass_1        0.000000      0.016895     0.021019   0.004056   0.000000
2  Pclass_2        0.088384      0.033063     0.028757   0.073735   0.112127
3     Sex_0        0.000000      0.067178     0.078667   0.032955   0.042291
4     Sex_1        0.005152      0.076932     0.068172   0.000000   0.069154

In [33]:
numeric_columns = importances.select_dtypes(include=[np.number])

In [34]:
importances["avg"] = numeric_columns.mean(axis=1)

In [35]:
importances = importances[["Feature", "avg"]]

In [36]:
importances = importances.sort_values(by="avg", ascending=False)

In [37]:
importances = importances[:50]

In [38]:
importances.head()

      Feature       avg
31  Initial_0  0.219033
2    Pclass_2  0.067213
3       Sex_0  0.044218
4       Sex_1  0.043882
19    Cabin_0  0.031452

In [39]:
train_importance = X_train[importances["Feature"].tolist()]
test_importance = X_test[importances["Feature"].tolist()]

In [40]:
train_importance.head()

,Initial_0,Pclass_2,Sex_0,Sex_1,Cabin_0,Initial_6,Fare_0,LowChance_0,HighChance_0,LowChance_1,...,Age_6,Family_0,Ticket_Num_Cut_3,Fare_3,Cabin_4,Ticket_Initial2_2,Cabin_1,Age_1,Ticket_Initial2_15,Family_4
0,1,1,1,0,1,0,1,1,1,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,1,0,0,...,0,0,1,1,0,0,1,0,0,0
2,0,1,0,1,1,0,1,1,1,0,...,0,1,0,0,0,1,0,0,0,0
3,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
4,1,1,1,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0

In [41]:
logreg_model = LogisticRegression()
svc_model = SVC()
decision_model = DecisionTreeClassifier()
random_model = RandomForestClassifier()
extra_model = ExtraTreesClassifier()
gbm_model = GradientBoostingClassifier()
nb_model = GaussianNB()
xgb_model = XGBClassifier(eval_metric="logloss")
lgbm_model = LGBMClassifier()

results = dict()

In [42]:
alg = logreg_model
alg.fit(train_importance, y_train)
train_accuracy = alg.score(train_importance, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [43]:
alg = svc_model
alg.fit(train_importance, y_train)
train_accuracy = alg.score(train_importance, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [44]:
alg = decision_model
alg.fit(train_importance, y_train)
train_accuracy = alg.score(train_importance, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [45]:
alg = random_model
alg.fit(train_importance, y_train)
train_accuracy = alg.score(train_importance, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [46]:
alg = extra_model
alg.fit(train_importance, y_train)
train_accuracy = alg.score(train_importance, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [47]:
alg = gbm_model
alg.fit(train_importance, y_train)
train_accuracy = alg.score(train_importance, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [48]:
alg = nb_model
alg.fit(train_importance, y_train)
train_accuracy = alg.score(train_importance, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [49]:
alg = xgb_model
alg.fit(train_importance, y_train)
train_accuracy = alg.score(train_importance, y_train)
results[alg.__class__.__name__] = train_accuracy * 100

In [50]:
sorted(results.items(), key=lambda x: x[1], reverse=True)

[('DecisionTreeClassifier', 94.69525959367945),
 ('RandomForestClassifier', 94.69525959367945),
 ('ExtraTreesClassifier', 94.69525959367945),
 ('XGBClassifier', 93.79232505643341),
 ('GradientBoostingClassifier', 87.92325056433408),
 ('SVC', 86.45598194130926),
 ('LogisticRegression', 85.32731376975168),
 ('GaussianNB', 79.68397291196389)]

In [51]:
import pickle

with open("titanic_step4_importance_train.pickle", "wb") as pickle_filename :
    pickle.dump(train_importance, pickle_filename)
with open("titanic_step4_importance_test.pickle", "wb") as pickle_filename :
    pickle.dump(test_importance, pickle_filename)
with open("titanic_step4_importance_train_y.pickle", "wb") as pickle_filename :
    pickle.dump(y_train, pickle_filename)

In [ ]:
import pickle